DROP TABLE IF EXISTS quizzes CASCADE;
CREATE TABLE quizzes (
  id SERIAL PRIMARY KEY NOT NULL,
  created_by INTEGER REFERENCES users(id) ON DELETE CASCADE,
  quiz_link TEXT NOT NULL,
  is_private BOOLEAN DEFAULT FALSE,
  category VARCHAR(255) NOT NULL
);